# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/park/dev/ROBOCUP/robocup2021/InstanceSegmentationAnnotationTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/park/dev/ROBOCUP/robocup2021/InstanceSegmentationAnnotationTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/park/dev/ROBOCUP/robocup2021/InstanceSegmentationAnnotationTool/CMakeFiles /home/park/dev/ROBOCUP/robocup2021/InstanceSegmentationAnnotationTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/park/dev/ROBOCUP/robocup2021/InstanceSegmentationAnnotationTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named InstanceSegmentationAnnotationTool

# Build rule for target.
InstanceSegmentationAnnotationTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InstanceSegmentationAnnotationTool
.PHONY : InstanceSegmentationAnnotationTool

# fast build rule for target.
InstanceSegmentationAnnotationTool/fast:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/build
.PHONY : InstanceSegmentationAnnotationTool/fast

#=============================================================================
# Target rules for targets named InstanceSegmentationAnnotationTool_autogen

# Build rule for target.
InstanceSegmentationAnnotationTool_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InstanceSegmentationAnnotationTool_autogen
.PHONY : InstanceSegmentationAnnotationTool_autogen

# fast build rule for target.
InstanceSegmentationAnnotationTool_autogen/fast:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool_autogen.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool_autogen.dir/build
.PHONY : InstanceSegmentationAnnotationTool_autogen/fast

InstanceSegmentationAnnotationTool_autogen/mocs_compilation.o: InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.o

.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.o

# target to build an object file
InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.o
.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.o

InstanceSegmentationAnnotationTool_autogen/mocs_compilation.i: InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.i

.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.i

# target to preprocess a source file
InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.i
.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.i

InstanceSegmentationAnnotationTool_autogen/mocs_compilation.s: InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.s

.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.s

# target to generate assembly for a file
InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.s
.PHONY : InstanceSegmentationAnnotationTool_autogen/mocs_compilation.cpp.s

qrc_InstanceSegmentationAnnotationTool.o: qrc_InstanceSegmentationAnnotationTool.cpp.o

.PHONY : qrc_InstanceSegmentationAnnotationTool.o

# target to build an object file
qrc_InstanceSegmentationAnnotationTool.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/qrc_InstanceSegmentationAnnotationTool.cpp.o
.PHONY : qrc_InstanceSegmentationAnnotationTool.cpp.o

qrc_InstanceSegmentationAnnotationTool.i: qrc_InstanceSegmentationAnnotationTool.cpp.i

.PHONY : qrc_InstanceSegmentationAnnotationTool.i

# target to preprocess a source file
qrc_InstanceSegmentationAnnotationTool.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/qrc_InstanceSegmentationAnnotationTool.cpp.i
.PHONY : qrc_InstanceSegmentationAnnotationTool.cpp.i

qrc_InstanceSegmentationAnnotationTool.s: qrc_InstanceSegmentationAnnotationTool.cpp.s

.PHONY : qrc_InstanceSegmentationAnnotationTool.s

# target to generate assembly for a file
qrc_InstanceSegmentationAnnotationTool.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/qrc_InstanceSegmentationAnnotationTool.cpp.s
.PHONY : qrc_InstanceSegmentationAnnotationTool.cpp.s

src/ISAT.o: src/ISAT.cpp.o

.PHONY : src/ISAT.o

# target to build an object file
src/ISAT.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/ISAT.cpp.o
.PHONY : src/ISAT.cpp.o

src/ISAT.i: src/ISAT.cpp.i

.PHONY : src/ISAT.i

# target to preprocess a source file
src/ISAT.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/ISAT.cpp.i
.PHONY : src/ISAT.cpp.i

src/ISAT.s: src/ISAT.cpp.s

.PHONY : src/ISAT.s

# target to generate assembly for a file
src/ISAT.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/ISAT.cpp.s
.PHONY : src/ISAT.cpp.s

src/InstanceSegmentationAnnotationTool.o: src/InstanceSegmentationAnnotationTool.cpp.o

.PHONY : src/InstanceSegmentationAnnotationTool.o

# target to build an object file
src/InstanceSegmentationAnnotationTool.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/InstanceSegmentationAnnotationTool.cpp.o
.PHONY : src/InstanceSegmentationAnnotationTool.cpp.o

src/InstanceSegmentationAnnotationTool.i: src/InstanceSegmentationAnnotationTool.cpp.i

.PHONY : src/InstanceSegmentationAnnotationTool.i

# target to preprocess a source file
src/InstanceSegmentationAnnotationTool.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/InstanceSegmentationAnnotationTool.cpp.i
.PHONY : src/InstanceSegmentationAnnotationTool.cpp.i

src/InstanceSegmentationAnnotationTool.s: src/InstanceSegmentationAnnotationTool.cpp.s

.PHONY : src/InstanceSegmentationAnnotationTool.s

# target to generate assembly for a file
src/InstanceSegmentationAnnotationTool.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/InstanceSegmentationAnnotationTool.cpp.s
.PHONY : src/InstanceSegmentationAnnotationTool.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/InstanceSegmentationAnnotationTool.dir/build.make CMakeFiles/InstanceSegmentationAnnotationTool.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... InstanceSegmentationAnnotationTool"
	@echo "... InstanceSegmentationAnnotationTool_autogen"
	@echo "... InstanceSegmentationAnnotationTool_autogen/mocs_compilation.o"
	@echo "... InstanceSegmentationAnnotationTool_autogen/mocs_compilation.i"
	@echo "... InstanceSegmentationAnnotationTool_autogen/mocs_compilation.s"
	@echo "... qrc_InstanceSegmentationAnnotationTool.o"
	@echo "... qrc_InstanceSegmentationAnnotationTool.i"
	@echo "... qrc_InstanceSegmentationAnnotationTool.s"
	@echo "... src/ISAT.o"
	@echo "... src/ISAT.i"
	@echo "... src/ISAT.s"
	@echo "... src/InstanceSegmentationAnnotationTool.o"
	@echo "... src/InstanceSegmentationAnnotationTool.i"
	@echo "... src/InstanceSegmentationAnnotationTool.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

